name: Build Docker Images only

on:
  push:
    branches: 
      - main
    pull_request:
      branches:
        - main
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      #   with:
      #     platforms: all

      # - name: Install Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      #     tags: |
      #       type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          # platforms: linux/amd64,linux/arm64
          # context: .
          push: false
          # tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}
